version: '3'
services:
  nextjs-app:
    container_name: dashboard-hfg
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: npm start